name: PERGEM Duyuru Botu

on:
  workflow_dispatch: {}
  schedule:
    - cron: "*/30 * * * *"  # Her 30 dakikada bir (UTC)

permissions:
  contents: write

concurrency:
  group: pergem-bot
  cancel-in-progress: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Repoyu çek
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Bağımlılıkları yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Botu çalıştır
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python bot.py

      - name: Durum dosyasını commit & push et (değiştiyse)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add last_pergem_duyuru.txt
            git commit -m "Update last_pergem_duyuru.txt [skip ci]"
            git push
          else
            echo "Değişiklik yok."
          fi
